
development:
  host: 127.0.0.1
  port: 27017
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false
  database: mongo_test_development

test:
  uri: <%= ENV['MONGOHQ_URL'] %>
  database: mongo_test
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  database: mongo_test
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false