defaults: &defaults
  host: 127.0.0.1
  port: 123456
  options:
    w: 1
    pool_size: 1
    slave_ok: false
    ssl: false

development:
  <<: *defaults
  port: 9999
  database: mongo_test_development

test:
  <<: *defaults
  port: 1001
  database: mongo_test_test
  w: 0

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGODB_URI'] %>
